#!/usr/bin/env python3

import argparse


# Picking this format mainly because it's part of the standard library.
import json

import os
import pathlib
import sys

def main():
    parser = argparse.ArgumentParser(
                        prog='dirmark',
                        description='directory bookmarker')
    subparsers = parser.add_subparsers(required=True)
    add_parser = subparsers.add_parser('add')
    add_parser.set_defaults(func=add_bookmark)
    add_parser.add_argument('directory', type=existing_dir)
    add_parser.add_argument('bookmarks', type=pathlib.Path)
    list_parser = subparsers.add_parser('list')
    list_parser.set_defaults(func=list_bookmarks)
    list_parser.add_argument('current_dir', type=existing_dir)
    list_parser.add_argument('bookmarks', type=argparse.FileType("r"))
    args = parser.parse_args()
    args.func(args)

def existing_dir(directory: str) -> str:
    if not os.path.isdir(directory):
        raise argparse.ArgumentTypeError()
    return directory

def add_bookmark(args):
    # This is the format.
    bm = {"bookmarks": []}
    if args.bookmarks.is_file():
        with open(args.bookmarks) as f:
            bm = json.load(f)

    bookmarks = [args.directory]

    for bookmark in bm["bookmarks"]:
        if os.path.isdir(bookmark) and bookmark != args.directory:
            bookmarks.append(bookmark)

    bm["bookmarks"] = bookmarks

    with open(args.bookmarks, "w") as f:
        json.dump(bm, f, indent=4)

def list_bookmarks(args):
    bookmarks = json.load(args.bookmarks)
    for bookmark in bookmarks["bookmarks"]:
        if bookmark != args.current_dir:
            print(bookmark)

if __name__ == '__main__':
    main()
