#!/usr/bin/env bash

while read -r selection; do
    echo "$selection"
    clear

    lines=$(tput lines)
    cols=$(tput cols)

    if [ -d "$selection" ]; then
    exa -a -G --group-directories-first --colour=always "$selection" | head -n "$lines"
    continue
    fi

    ext="${selection##*.}"

    if [[ "$ext" == "rm" ]]; then
        wezterm imgcat "$(vidthumb "$selection")"
        continue
    fi

    filetype="$(file -Lb --mime-type "$selection")"

    if [[ "$filetype" =~ ^image ]]; then
        wezterm imgcat "$selection"
        continue
    fi

    if [[ "$filetype" =~ ^video ]]; then
        # vidthumb is from here:
        # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
        wezterm imgcat "$(vidthumb "$selection")"
        continue
    fi

    if [[ "$filetype" == "application/pdf" ]]; then
        system="$(uname -s)"

        if [[ "$system" == "Darwin" ]]; then
            sips -s format png --out ~/.cache/pdf_preview.png "$selection"
            wezterm imgcat ~/.cache/pdf_preview.png
            rm -f ~/.cache/pdf_preview.png
            continue
        fi

        if [[ "$system" == "Linux" ]]; then
            convert "$selection"[0] ~/.cache/pdf_preview.png
            wezterm imgcat ~/.cache/pdf_preview.png
            rm -f ~/.cache/pdf_preview.png
            continue
        fi
    fi

    pistol "$selection"
done </tmp/nnn.fifo
