#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "${file##*.}" == "rm" ]]; then
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "$file")"
    exit 1
fi 

filetype="$( file -Lb --mime-type "$file")"

if [[ "$filetype" =~ ^image ]]; then
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$file"
    exit 1
fi

if [[ "$filetype" == "application/pdf" ]]; then
    system="$(uname -s)"

    if [[  "$system" == "Darwin" ]]; then
        sips -s format png --out ~/.cache/pdf_preview.png "$file"
        kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" ~/.cache/pdf_preview.png
        rm -f ~/.cache/pdf_preview.png
        exit 1
    fi;

    if [[  "$system" == "Linux" ]]; then
        convert "$file"[0] ~/.cache/pdf_preview.png
        kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" ~/.cache/pdf_preview.png
        rm -f ~/.cache/pdf_preview.png
        exit 1
    fi;
fi

if [[ "$filetype" =~ ^video ]]; then
    # vidthumb is from here:
    # https://raw.githubusercontent.com/duganchen/kitty-pistol-previewer/main/vidthumb
    kitty +icat --silent --transfer-mode file --place "${w}x${h}@${x}x${y}" "$(vidthumb "$file")"
    exit 1
fi

pistol "$file"
