# This should be standard boilerplate. But for transparency, they're from here:
# https://youtu.be/XivdyrFCV4M?si=-SNCQgclCAlZwSYl
# https://github.com/tonybanters/tmux-btw/blob/master/tmux.conf
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on

# https://www.terminal.guide/tools/multiplexer/tmux/copy-mode-guide/
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"

setw -g mode-keys vi
set -g set-clipboard off

# Let's leave this out and and leave it terminal-theme-agnostic
# run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux .
