# Standard boilerplate for a current tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
# From tmux-sensible
set -g focus-events on
set -g display-time 4000
set -g status-interval 5

# These are currently the correct settings for Linux. All terminals
# (tested with Ghostty and Ptyxis)
# https://www.terminal.guide/tools/multiplexer/tmux/copy-mode-guide/
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
set -g set-clipboard off

setw -g mode-keys vi

# This certainly has some ideas
# https://subdepthtech.com/posts/tmux-ghostty-terminal-workflow/

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# Yeah these are better
unbind \"
unbind "%"
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "|" split-window -h -c "#{pane_current_path}"
