# This breaks Azahar. Why ddid I have it set?
# QT_QPA_PLATFORM=wayland
#QT_QPA_PLATFORMTHEME=qt6ct
# And then you need this for QML applications like YACReaderLibrary:
# sudo dnf install kf6-qqc2-desktop-style kf5-qqc2-desktop-style
QT_STYLE_OVERRIDE=kvantum
# Then do this
# flatpak override --user --env=QT_STYLE_OVERRIDE=kvantum --filesystem=xdg-config/Kvantum:ro
# re: https://discussion.fedoraproject.org/t/can-you-actually-apply-custom-kvantum-themes-to-flatpak-apps/115983
